# This is a TOML document. Boom
[discovery]
    nodes = ["10.100.55.79:7171"]

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["10.100.55.62:9092","10.100.55.63:9092","10.100.55.64:9092"]
